### ISSUE TITLE
Cannot install nativescript-ng2-magic

### ISSUE THREAD

**Issue by marijanam** [NathanWalker/nativescript-ng2-magic#11] opened 2016-06-22 12:29 UTC
Hi,
I'am new to the angular2 and nativescript. I was trying to follow this tutorial https://www.youtube.com/watch?v=T2wAb6UX8zo. 

I can't install nativescript-ng2-magic, after the command **npm i nativescript-ng2-magic** I'm getting this error:

Installing NativeScript Angular 2 Template...
Unable to use template https://github.com/NativeScript/template-hello-world-ng. Make sure you've specified valid name, github URL or path to local dir.
Error is: No compatible version found: tns-core-modules@'>=2.1.0 <3.0.0'

and at the end of the log:

node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! nativescript-ng2-magic@1.5.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-ng2-magic@1.5.7 postinstall script 'node install.js'.

If someone can help me, tnx!

**Comment by NathanWalker** [comment] 2016-06-22 16:42
Sounds like you got this to work? If so, please close 👍

**Comment by marijanam** [comment] 2016-06-23 06:44
No, I still can't install nativescript-ng2-magic. I'am getting the error mentioned in comment above.

> nativescript-ng2-magic@1.5.7 postinstall /Users/maja/angular/maja/shop/node_modules/nativescript-ng2-magic
> node install.js

Installing NativeScript Angular 2 Template...
Unable to use template https://github.com/NativeScript/template-hello-world-ng. Make sure you've specified valid name, github URL or path to local dir.
Error is: No compatible version found: tns-core-modules@'>=2.1.0 <3.0.0'

**Comment by shripalsoni04** [comment] 2016-06-26 20:38
Hi @marijanam , the issue is 2.1.0 version of tns-core-modules does not exist yet, and in `package.json` of [`template-hello-work-ng`](https://github.com/NativeScript/template-hello-world-ng), it is written as 2.1.0 instead of 2.0.1 for tns-core-modules dependency.

I have created PR at https://github.com/NativeScript/template-hello-world-ng/pull/20. The issue should be solved once it is merged.

@NathanWalker It will be great if you can update peerDependency of angular modules'  to `2.0.0-rc.3`, as currently it is set at `2.0.0-rc.1` and we cannot use it with fresh installation using angular-cli command, `ng new my-app`.

**Comment by NathanWalker** [comment] 2016-06-27 04:31
@shripalsoni04 I just published `1.5.8` which uses rc.3 👍  ... Not sure status on updating the template but I posted this comment so hopefully it will be addressed on Monday: https://github.com/NativeScript/template-hello-world-ng/pull/20#issuecomment-228635177

**Comment by NathanWalker** [comment] 2016-06-27 04:34
Actually `1.6.0` is latest, had to fix deps.

**Comment by NathanWalker** [comment] 2016-07-07 06:34
Template has been updated to use rc.3 now: https://github.com/NativeScript/template-hello-world-ng/blob/master/package.json

**Closed as completed by NathanWalker** 2016-07-07 06:34 UTC
